# Generated by Django 4.0.10 on 2024-05-18 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Professionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Professionals.domain'),
        ),
    ]
