# Generated by Django 4.0.10 on 2024-05-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceRequest', '0003_alter_servicerequest_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
