# Generated by Django 4.0.10 on 2024-05-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceRequest', '0005_alter_servicerequest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=9),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='urgency',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=6),
        ),
    ]
