# Generated by Django 4.0.10 on 2024-05-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceRequest', '0007_alter_servicerequest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
